# Generated by Django 4.1.6 on 2023-03-06 09:20

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalconyOrLoggiaChoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DetachedHouse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('street', models.CharField(max_length=255, verbose_name='Улица')),
                ('year_construction', models.PositiveIntegerField(verbose_name='Год постройки')),
                ('home', models.PositiveIntegerField(verbose_name='Дом')),
                ('realty_type', models.CharField(choices=[('Кирпич', 'Кирпич'), ('Монолит', 'Монолит'), ('Панельный', 'Панельный')], default='Монолит', max_length=255, verbose_name='Тип дома')),
                ('floor_in_house', models.PositiveIntegerField(verbose_name='Количество этажей')),
                ('bathroom_location', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('In street', 'На улице'), ('In house', 'В доме')], max_length=9, verbose_name='Местоположение санузлов')),
                ('distance_to_city_center', models.PositiveIntegerField(verbose_name='Расстояние до центра, км')),
                ('communications', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Water', 'Вода'), ('Light', 'Свет'), ('Gas', 'Газ')], max_length=5, verbose_name='Коммуникации')),
                ('land_area', models.PositiveIntegerField(verbose_name='Площадь участка')),
                ('home_area', models.PositiveIntegerField(verbose_name='Жил площадь')),
                ('water_type', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Pit', 'Колодец'), ('Borehole', 'Скважина'), ('Сentral', 'Центральное')], max_length=9, verbose_name='Источник воды')),
                ('severage_type', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Central', 'Центральная'), ('Local', 'Локальная')], max_length=12, verbose_name='Тип канализации')),
                ('quantity_rooms', models.PositiveIntegerField(verbose_name='Количество комнат')),
            ],
            options={
                'verbose_name': 'Частный дом',
                'verbose_name_plural': 'Частные дома',
            },
        ),
        migrations.CreateModel(
            name='FurnitureChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Мебель',
            },
        ),
        migrations.CreateModel(
            name='LandPlot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('street', models.CharField(max_length=255, verbose_name='Улица')),
                ('land_area', models.PositiveIntegerField(verbose_name='Площадь участка')),
                ('is_water', models.BooleanField(verbose_name='Вода')),
                ('is_severage', models.BooleanField(verbose_name='Канализация')),
                ('is_gas', models.BooleanField(verbose_name='Газ')),
                ('land_type', models.CharField(choices=[('ИЖС', 'ИЖС'), ('СНТ', 'СНТ')], max_length=3, verbose_name='Участок')),
            ],
            options={
                'verbose_name': 'Земельный участок',
                'verbose_name_plural': 'Земельные участки',
            },
        ),
        migrations.CreateModel(
            name='MultiStoreyBuilding',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('street', models.CharField(max_length=255, verbose_name='Улица')),
                ('year_construction', models.PositiveIntegerField(verbose_name='Год постройки')),
                ('home', models.PositiveIntegerField(verbose_name='Дом')),
                ('realty_type', models.CharField(choices=[('Кирпич', 'Кирпич'), ('Монолит', 'Монолит'), ('Панельный', 'Панельный')], default='Монолит', max_length=255, verbose_name='Тип дома')),
                ('floor_in_house', models.PositiveIntegerField(verbose_name='Количество этажей')),
                ('elevator', models.BooleanField(verbose_name='Лифт')),
            ],
            options={
                'verbose_name': 'Многоэтажка',
                'verbose_name_plural': 'Многоэтажки',
            },
        ),
        migrations.CreateModel(
            name='TechnicChoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Техника',
            },
        ),
        migrations.CreateModel(
            name='SaleRealty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Продажа',
                'verbose_name_plural': 'Продажа',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_area', models.PositiveIntegerField(blank=True, null=True, verbose_name='Площадь комнаты')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Комната',
                'verbose_name_plural': 'Комнаты',
            },
        ),
        migrations.CreateModel(
            name='RentalRealty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smoke', models.BooleanField(verbose_name='Можно курить')),
                ('child', models.BooleanField(verbose_name='Можно с детьми')),
                ('animal', models.BooleanField(verbose_name='Можно с животными')),
                ('sleeping_place', models.IntegerField(default=1, verbose_name='Количество спальных мест')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Аренда',
                'verbose_name_plural': 'Аренда',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='photos/')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Фотография',
                'verbose_name_plural': 'Фотографии',
            },
        ),
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bathroom_quantity', models.IntegerField(default=1, verbose_name='Число санузлов')),
                ('bathroom_type', multiselectfield.db.fields.MultiSelectField(choices=[('Separate', 'Раздельный'), ('Adjective', 'Смежный')], max_length=10, verbose_name='Типы санузлов')),
                ('floor', models.IntegerField(verbose_name='Этаж')),
                ('is_balcony_or_loggia', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Balcony', 'Балкон'), ('Loggia', 'Лоджия')], max_length=7, verbose_name='Балкон / лоджия')),
                ('rooms_type', models.CharField(choices=[('Смежный', 'Смежный'), ('Раздельный', 'Раздельный')], max_length=255, verbose_name='Тип комнат')),
                ('renovation', models.CharField(blank=True, choices=[('Евро', 'Евро'), ('Косметический', 'Косметический'), ('Капитальный', 'Капитальный'), ('Дизайнерский', 'Дизайнерский')], max_length=255, verbose_name='Ремонт')),
                ('home_area', models.PositiveIntegerField(verbose_name='Жил площадь')),
                ('flat', models.PositiveIntegerField(verbose_name='Квартира')),
                ('quantity_rooms', models.PositiveIntegerField(verbose_name='Количество комнат')),
                ('furniture', models.ManyToManyField(blank=True, max_length=512, to='agency.furniturechoice', verbose_name='Мебель')),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency.multistoreybuilding')),
                ('technic', models.ManyToManyField(blank=True, to='agency.technicchoices', verbose_name='Техника')),
            ],
            options={
                'verbose_name': 'Квартира',
                'verbose_name_plural': 'Квартиры',
            },
        ),
    ]
